wandb_version: 1

Notes:
  desc: null
  value: Default Hyper Parameters, Swish activation.
_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: huggingface
    huggingface_version: 4.18.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    start_time: 1651263527
    t:
      1:
      - 3
      - 11
      - 49
      - 55
      2:
      - 3
      - 11
      - 49
      - 55
      3:
      - 13
      - 16
      4: 3.6.9
      5: 0.12.15
      6: 4.18.0
      8:
      - 5
